### PR TITLE
Delete Makefile

### PR DESCRIPTION
**Pull request by bernadeth10**

### CODE REVIEW

**Comment by dontcallmedom** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by dirkschulze** [comment]
Why would we need to remove the make file? Looking at it, it should still work and create a versioned spec.

**Comment by bernadeth10** [comment]
BBFdelete everything
we dont make nothing pls delete 

Em Sex 19/10/04 14:18, Dirk Schulze notifications@github.com escreveu:

Why would we need to remove the make file? Looking at it, it should still work and create a versioned spec.

**Comment by AmeliaBR** [comment]
That's the main build file for the repo. It may be old-fashioned, but it still works.

**Pull request closed without merging**
