### PR TITLE
Fix missing trailing wsp after path commands

### PR DESCRIPTION
**Pull request by JeremiePat**
Hello SVG WG.

I'm currently implementing an SVG Path parser and it appears that the SVG2 path grammar is a little inconsistent with SVG 1.1 and with other current implementations (AFAIK those from web browsers).

Many details have been discussed in issue #752 (mostly point 1 and 2 raised by @dalboris)

This PR is a proposed fix for the missing trailing white spaces after commands and at end of path. The intent is to prevent a breaking change to the SVG Path grammar. If the SVG WG think this breaking change should be kept, so it should be clearly stated (exactly like the warn done for numbers with trailing dot). If so, I would be glad to update this PR accordingly.

+@dalboris

### CODE REVIEW

**Comment by JeremiePat** [comment]
Ah! This my first PR to W3C so I forgot to link my GitHub account. It is done, feel free to revalidate the check 😉

**Comment by dalboris** [comment]
Good initiative. I was waiting for more feedback from the committee to know whether I should submit a PR to fix/improve the grammar.

In general, I personally favor a concise grammar, more info here: 

https://github.com/w3c/svgwg/issues/751

In the specific case of the trailing whitespaces, here is what I advocate:

https://github.com/w3c/svgwg/issues/751#issuecomment-555163624

```
svg_path ::= wsp* (moveto (wsp* drawto_command)*)? wsp*
```

It is equivalent to your:

```
svg_path::= wsp* (moveto wsp* drawto_command_group*)? wsp*
drawto_command_group::=
    drawto_command
    | drawto_command wsp* drawto_command_group
```

But without the additional symbol `drawto_command_group` which makes the grammar three lines longer and harder for humans to parse. Less symbols = less cognitive load, in my opinion.

**Comment by JeremiePat** [comment]
I totally agree with you that a shorter grammar definition would be helpful to spec implementer. It took me three iterations banging my head on a wall to start having a reasonable understanding of the path grammar. I would love to have seen issue #751 earlier to avoid that 😋. FWIW I would support a shorter, cleaner, version of the grammar either in the next iteration of the SVG Spec or within the dedicated [Path Spec](https://svgwg.org/specs/paths/).

For that fix, the first suggestion I made was a direct inspiration from SVG 1.1, but I really like your suggestion to shorten this PR. However, I'm not super at ease with nesting parenthesis. This is one of this case that make things a little harder to process for a human brain (at least, mine)

I was considering something like this (yes, still an additional symbol):

```
svg_path::= wsp* (moveto wsp* drawto_command_group*)?
drawto_command_group::= (drawto_command wsp*)+
```

There is also the option to add a `wsp*` symbol at the end of each command definition and simplify the grammar to:

```
svg_path::= wsp* (moveto drawto_command*)?
```

**Comment by dalboris** [comment]
> It took me three iterations banging my head on a wall to start having a reasonable understanding of the path grammar. 

Same here :)

Thx for the amend to your PR! I do find this 1-liner version the most readable despite the nested parentheses, but it's obviously very subjective.

Note that in your 2-line suggestion above, the `+` in `(drawto_command wsp*)+` is redundant with the `*` in `drawto_command_group*` (in other words, `(A+)*` and `A*` are equivalent), so you could simplify the suggestion to:

```
svg_path::= wsp* (moveto wsp* drawto_command_group*)?
drawto_command_group::= drawto_command wsp*
```

(in which case the name `drawto_command_group` should obviously be changed, e.g. to `command_wsp`, but then since it's so simple and only used once... well, we might as well inline it and avoid finding a good name ;) )

**Comment by dalboris** [comment]
Re adding `wsp*` at the end of each command definition: we could even go further and add `wsp*` also at the beginning of each command. This way, we would have:

```
svg_path::= (moveto drawto_command*)?
```

This restores symmetry, otherwise readers might otherwise wonder which there is `wsp*` at the end of each command, but not at the beginning.

Either way, I'm not sure it's worth the added noise in each command. Reading such grammar, I would probably tell myself: why on earth didn't they factorize these `wsp*`?

**Comment by dalboris** [comment]
@tabatkins @caribouW3 Would one of you, or another member of the committee with merge power, be willing to review and merge this change? It's a one-line fix of a bug in the grammar, that was unintentionally introduced when modifying the grammar from SVG 1.1 to 2.0. 

This issue has already been reported several times, the last one being: https://github.com/w3c/svgwg/issues/929

**Comment by dalboris** [comment]
Thanks @caribouW3 for merging!

Note: it is also now possible to close this issue: https://github.com/w3c/svgwg/issues/807

**Pull request merged**
