### PR TITLE
Replace void with undefined in Web IDL

### PR DESCRIPTION
**Pull request by foolip**
See https://github.com/heycam/webidl/pull/906.

### CODE REVIEW

**Comment by foolip** [comment]
@tabatkins can you review?

**Comment by foolip** [comment]
@saschanaz FYI

**Comment by saschanaz** [comment]
> @saschanaz FYI

Depends on https://github.com/w3c/browser-specs/issues/215.

**Comment by foolip** [comment]
@tabatkins I see that https://svgwg.org/svg2-draft/ isn't updated, is there a manual build/deploy step needed?

**Comment by tabatkins** [comment]
I haven't a clue. @AmeliaBR or @heycam?

**Pull request merged**
