### PR TITLE
Remove mesh gradients

### PR DESCRIPTION
**Pull request by dstorey**

### CODE REVIEW

**Comment by dstorey** [comment]
These will probably all need an additional sweep to remove all the demo files and illustrations from the source that are no longer linked. We can probably do that all at once as a clean up task.

**Comment by AmeliaBR** [comment]
For the changelog, for this and the hatch PR, maybe make it explicit that this is a "defer" instead of a "remove for ever"?

**Comment by dstorey** [comment]
How about now?

**Comment by dstorey** [comment]
New bug is #454  and I've created the SVG2/21 tags

**Comment by dstorey** [comment]
Merging these two as I just realized Dirk had approved them. We can massage the wording if they need changing all together in a new PR.

**Pull request merged**
